FROM node:22
RUN apt-get update && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY . .
RUN npm install
ARG API_DB_URL
ENV DATABASE_URL=$API_DB_URL
ENTRYPOINT ["sh", "-c"]
CMD ["npm start"]