name: Deploy Migrations

on:
  push:
    branches:
      - develop
    paths:
      - "database/migrations/**"

jobs:
  migrate:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run Flyway migrations
        run: |
          wget https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/7.8.2/flyway-commandline-7.8.2-linux-x64.tar.gz
          tar -xvf flyway-commandline-7.8.2-linux-x64.tar.gz
          sudo ln -s $PWD/flyway-7.8.2/flyway /usr/local/bin/flyway || true
          flyway -url='${{ secrets.DEV_DB_URL }}' -user='${{ secrets.DEV_DB_USER }}' -password='${{ secrets.DEV_DB_PASSWORD }}' -locations=filesystem:./database/migrations -outOfOrder=true -baselineOnMigrate=true -connectRetries=5 migrate
